
import React from 'react';
import {
    Lightbulb,
    BookOpen,
    Settings,
    LayoutDashboard,
    FileText,
    AlertTriangle,
    AlertCircle,
    CheckCircle,
    XCircle,
    Clock,
    Info,
    X,
    Loader2,
    Send,
    Menu,
    Trash,
    Pencil,
    Edit,
    Archive,
    Calendar,
    Sparkles,
    WandSparkles,
    ChevronLeft,
    ChevronRight,
    PlusCircle,
    RefreshCw,
    Eye,
    ExternalLink,
    Zap,
    Image,
    Shield,
    TrendingUp,
    BarChart3,
    Globe,
    Search,
    Target,
    BarChart,
    MousePointer,
    Activity,
    Play,
    Server,
    Database,
    TextCursor,
    Brain
} from 'lucide-react';

// Re-export lucide-react icons to keep existing component names and imports stable
export {
    Lightbulb,
    BookOpen,
    Settings,
    LayoutDashboard,
    FileText,
    AlertTriangle,
    AlertCircle,
    CheckCircle,
    XCircle,
    Clock,
    Info,
    X,
    Send,
    Menu,
    Trash,
    Pencil,
    Edit,
    Archive,
    Calendar,
    Sparkles,
    WandSparkles,
    ChevronLeft,
    ChevronRight,
    PlusCircle,
    RefreshCw,
    Eye,
    ExternalLink,
    Zap,
    Image,
    Shield,
    TrendingUp,
    BarChart3,
    Globe,
    Search,
    Target,
    BarChart,
    MousePointer,
    Activity,
    Play,
    Server,
    Database,
    TextCursor,
    Brain
};

// Provide a Spinner alias using a Lucide loader icon for backward compatibility
export const Spinner: React.FC<{ className?: string; style?: React.CSSProperties; }> = ({ className, style }) => (
    <Loader2 className={className} style={style} />
);
